language: java
jdk:
- openjdk11
cache:
  directories:
    - ~/.m2/repository

install: mvn -s .mvn.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

script: mvn clean test jacoco:report coveralls:report

before_deploy:
- openssl aes-256-cbc -K $encrypted_72f0bb93708b_key -iv $encrypted_72f0bb93708b_iv -in my-private-key.asc..enc -out my-private-key.asc. -d
- gpg --import my-private-key.asc.

deploy:
  provider: script
  script: mvn clean deploy -s .mvn.xml -DskipTests=true -B -U -P release
  skip_cleanup: true
  on:
    tags: true
